In [1]:
import numpy as np

In [2]:
# The 'loadtxt()' function can be used to load data from a file into an array.
x = np.loadtxt('myno.txt')
print(x)

# This will do sum of the numbers of 'myno.txt' file
print(np.sum(x))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
550.0


In [3]:
x = np.loadtxt('mynos.txt')
print(x)

[[ 10.  20.  30.  40.  50.]
 [100. 200. 300. 400. 500.]
 [  1.   2.   3.   4.   5.]
 [ 11.  22.  33.  44.  55.]]


In [4]:
a, b, c, d = np.loadtxt('mynos.txt')
print("a = ",a)
print("b = ",b)
print("c = ",c)
print("d = ",d)

a =  [10. 20. 30. 40. 50.]
b =  [100. 200. 300. 400. 500.]
c =  [1. 2. 3. 4. 5.]
d =  [11. 22. 33. 44. 55.]


In [6]:
# This will generate the missing numbers as 'nan' in file 'missingnos.txt'
x = np.genfromtxt('missingnos.txt')
print(x)

[[ 10.  nan  30.  nan  50.]
 [100. 200.  nan 400.  nan]
 [ nan  20.  nan  40.  nan]
 [ 10.  nan  30.  nan  50.]]


In [7]:
a, b, c, d = np.genfromtxt('missingnos.txt')
print(a)
print(sum(a))

[10. nan 30. nan 50.]
nan


In [8]:
# This will replace value of 'nan' as '0'
x = np.genfromtxt('missingnos.txt', filling_values = 0)
print(x)

[[ 10.   0.  30.   0.  50.]
 [100. 200.   0. 400.   0.]
 [  0.  20.   0.  40.   0.]
 [ 10.   0.  30.   0.  50.]]


In [9]:
a, b, c, d = np.genfromtxt('missingnos.txt', filling_values = 0)
print(a)
print(sum(a))

[10.  0. 30.  0. 50.]
90.0


In [10]:
# The 'save()' function is used to save a numpy array to a file
x = np.array([110, 230, 320, 4, 5, 650, 7, 830, 910, 10])
np.savetxt('storenos.txt', x, delimiter = ",")
# Delimiter will separate the values & write in new line

In [11]:
x = np.loadtxt('storenos.txt')
print(x)

[110. 230. 320.   4.   5. 650.   7. 830. 910.  10.]
